services:
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    restart: always
    networks:
      - internal-network    
    ports:
      - "${PORT_NGINX}:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
     - generate-service-deploy 
     - generate-service-ui
     - generate-service-rest
    depends_on:
     - generate-service-rest
     - generate-service-deploy 
     - generate-service-ui
  generate-service-deploy:
    image: lorenzolince/generate-service-deploy
    container_name: generate-service-deploy
    hostname: generate-service-deploy
    user: "app:app" 
    restart: always
    networks:
      - internal-network
    volumes:
    - /app/service
    - ./templates:/app/deploy/templates:rw
    - ./input:/app/deploy/input:rw
    environment:
    - GRAPHQL_SPQR_HTTP_ENDPOINT=graphql
    - ENDPOINT_SERVICES=${ENDPOINT_SERVICES}
    #- PDF_TEMPLATE_PATH=/app/deploy/templates
    #- PDF_SIGN_PFX=stringBase64
    #- PDF_SIGN_CERT=stringBase64
    #- SWAGGER_UI=true
    #- SFTP_KEY=stringBase64
    #- SFTP_USERNAME=internal
    #- LOCAL_PATH=/app/deploy/templates
    #- FILE_DIRECTORY_INPUT=input/
    #- SMB_HOST=192.168.0.
    #- SMB_PORT=445
    #- SMB_DOMAIN=WORKGROUP
    #- SMB_USER=lopa
    #- SMB_PASSWORD=123456
    #- SMB_SHARE_NAME_BASE=share
    #extra_hosts:
    #- sftp.server.test:192.168.0.
  generate-service-rest:
    image: lorenzolince/generate-service-rest
    container_name: generate-service-rest
    hostname: generate-service-rest
    restart: always
    networks:
      - internal-network
    volumes_from:
      - generate-service-deploy:rw
    volumes:
    - ./data:/app/data
    links:
     - generate-service-deploy 
    environment:
    - URL_REPOSITORY=${URL_REPOSITORY}
  generate-service-ui:
    image: lorenzolince/generate-service-ui
    container_name: generate-service-ui
    hostname: generate-service-ui
    restart: always
    networks:
      - internal-network
    environment:
    - NODE_ENV=test
    - PORT=3000
    links:
     - generate-service-rest
    depends_on:
     - generate-service-rest
     
networks:
  internal-network:
    driver: bridge  
    
